security:
    encoders:
        App\Entity\Users:
            algorithm: bcrypt
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers

    role_hierarchy:
        ROLE_USER: ROLE_USER
        ROLE_ADMIN: ROLE_ADMIN
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]


    providers:
        in_database: 
            entity:
                class: App\Entity\Users
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: true
            provider: in_database
        
            form_login:
                login_path: account_login
                check_path: account_login
                default_target_path: home
            logout:
                path: account_logout
                target: home

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }     
            # https://symfony.com/doc/current/security/form_login_setup.html
